-- dbo.aplicacao definition

-- Drop table

-- DROP TABLE dbo.aplicacao;

CREATE TABLE dbo.aplicacao (
	id_aplicacao uuid DEFAULT gen_random_uuid() NOT NULL,
	nome varchar NOT NULL,
	descricao varchar NULL,
	CONSTRAINT aplicacao_pkey PRIMARY KEY (id_aplicacao)
);


-- dbo.campanha definition

-- Drop table

-- DROP TABLE dbo.campanha;

CREATE TABLE dbo.campanha (
	id bigserial NOT NULL,
	nome varchar(255) NOT NULL,
	mensagem text NOT NULL,
	lista_contato jsonb NOT NULL,
	dt_inicio timestamptz NOT NULL,
	dt_fim timestamptz NOT NULL,
	dias_semana _text NOT NULL,
	fl_ativo bool DEFAULT true NOT NULL,
	account int8 NOT NULL,
	inbox int8 NOT NULL,
	link_media text NULL,
	media_type varchar(50) NULL,
	mime_type varchar(100) NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	horario_disparo time NULL,
	ultimo_envio_em timestamptz NULL,
	CONSTRAINT campanha_pkey PRIMARY KEY (id),
	CONSTRAINT chk_dt_periodo CHECK ((dt_fim > dt_inicio)),
	CONSTRAINT chk_media_type CHECK ((((media_type)::text = ANY ((ARRAY['image'::character varying, 'video'::character varying, 'audio'::character varying, 'document'::character varying])::text[])) OR (media_type IS NULL)))
);


-- dbo.campanha_logs definition

-- Drop table

-- DROP TABLE dbo.campanha_logs;

CREATE TABLE dbo.campanha_logs (
	id_campanha_logs serial4 NOT NULL,
	id_campanha int4 NOT NULL,
	numero varchar(20) NOT NULL,
	status bool DEFAULT false NULL,
	msg_resposta_evolution text NULL,
	created timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT campanha_logs_pkey PRIMARY KEY (id_campanha_logs)
);


-- dbo.documents definition

-- Drop table

-- DROP TABLE dbo.documents;

CREATE TABLE dbo.documents (
	id bigserial NOT NULL,
	"content" text NULL,
	metadata jsonb NULL,
	embedding dbo.vector NULL,
	titulo text NULL,
	CONSTRAINT documents_pkey PRIMARY KEY (id)
);


-- dbo.empresa definition

-- Drop table

-- DROP TABLE dbo.empresa;

CREATE TABLE dbo.empresa (
	id_empresa uuid DEFAULT gen_random_uuid() NOT NULL,
	nome varchar NOT NULL,
	criado_em timestamp DEFAULT now() NOT NULL,
	fl_ativo int2 DEFAULT 1 NOT NULL,
	CONSTRAINT empresa_fl_ativo_check CHECK ((fl_ativo = ANY (ARRAY[0, 1]))),
	CONSTRAINT empresa_pkey PRIMARY KEY (id_empresa)
);


-- dbo.historico_mensagens definition

-- Drop table

-- DROP TABLE dbo.historico_mensagens;

CREATE TABLE dbo.historico_mensagens (
	id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	id_usuario text NULL,
	mensagem_usuario text NULL,
	mensagem_agente text NULL,
	telefone text NULL,
	nome_usuario text NULL,
	id_conversa text NULL,
	message_type text NULL,
	ativo bool DEFAULT true NULL,
	nome_app text DEFAULT 'delivery'::text NULL,
	CONSTRAINT historico_mensagens_pkey PRIMARY KEY (id)
);


-- dbo.historico_mensagens_simples definition

-- Drop table

-- DROP TABLE dbo.historico_mensagens_simples;

CREATE TABLE dbo.historico_mensagens_simples (
	id serial4 NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	texto text NOT NULL,
	chat_id varchar(255) NOT NULL,
	CONSTRAINT historico_mensagens_simples_pkey PRIMARY KEY (id)
);


-- dbo.leads definition

-- Drop table

-- DROP TABLE dbo.leads;

CREATE TABLE dbo.leads (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	"Telefone" text NULL,
	"Nome" text NULL,
	CONSTRAINT lead_pkey PRIMARY KEY (id)
);


-- dbo.mensagens definition

-- Drop table

-- DROP TABLE dbo.mensagens;

CREATE TABLE dbo.mensagens (
	id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	telefone text NULL,
	id_conversa text NULL,
	update_at timestamptz DEFAULT now() NULL,
	nome_app text DEFAULT 'delivery'::text NULL,
	CONSTRAINT mensagens_pkey PRIMARY KEY (id)
);


-- dbo.usuario definition

-- Drop table

-- DROP TABLE dbo.usuario;

CREATE TABLE dbo.usuario (
	id_usuario uuid DEFAULT gen_random_uuid() NOT NULL,
	nome varchar NOT NULL,
	email varchar NOT NULL,
	senha_hash text NULL,
	criado_em timestamp DEFAULT now() NOT NULL,
	fl_ativo int2 DEFAULT 1 NOT NULL,
	CONSTRAINT usuario_email_key UNIQUE (email),
	CONSTRAINT usuario_fl_ativo_check CHECK ((fl_ativo = ANY (ARRAY[0, 1]))),
	CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario)
);


-- dbo.agente definition

-- Drop table

-- DROP TABLE dbo.agente;

CREATE TABLE dbo.agente (
	id_agente uuid DEFAULT gen_random_uuid() NOT NULL,
	id_empresa uuid NOT NULL,
	nome varchar NOT NULL,
	descricao text NULL,
	modelo_llm varchar NULL,
	criado_em timestamp DEFAULT now() NOT NULL,
	fl_ativo int2 DEFAULT 1 NOT NULL,
	CONSTRAINT agente_fl_ativo_check CHECK ((fl_ativo = ANY (ARRAY[0, 1]))),
	CONSTRAINT agente_pkey PRIMARY KEY (id_agente),
	CONSTRAINT fk_ag_empresa FOREIGN KEY (id_empresa) REFERENCES dbo.empresa(id_empresa)
);


-- dbo.agente_config definition

-- Drop table

-- DROP TABLE dbo.agente_config;

CREATE TABLE dbo.agente_config (
	id_agente_config uuid DEFAULT gen_random_uuid() NOT NULL,
	id_agente uuid NOT NULL,
	gerar_historico bool DEFAULT true NOT NULL,
	criado_em timestamp DEFAULT now() NOT NULL,
	fl_ativo int2 DEFAULT 1 NOT NULL,
	agent_id varchar NULL,
	agent_alias_id varchar NULL,
	region varchar NULL,
	endpoint_url text NULL,
	credentials_ref text NULL,
	params_json jsonb DEFAULT '{}'::jsonb NULL,
	CONSTRAINT agente_config_fl_ativo_check CHECK ((fl_ativo = ANY (ARRAY[0, 1]))),
	CONSTRAINT agente_config_id_agente_key UNIQUE (id_agente),
	CONSTRAINT agente_config_pkey PRIMARY KEY (id_agente_config),
	CONSTRAINT fk_agcfg_agente FOREIGN KEY (id_agente) REFERENCES dbo.agente(id_agente)
);


-- dbo.canal_whatsapp definition

-- Drop table

-- DROP TABLE dbo.canal_whatsapp;

CREATE TABLE dbo.canal_whatsapp (
	id_canal_whatsapp uuid DEFAULT gen_random_uuid() NOT NULL,
	id_empresa uuid NOT NULL,
	numero_e164 varchar NOT NULL,
	nome_agente varchar NULL,
	fl_ativo int2 DEFAULT 1 NOT NULL,
	CONSTRAINT canal_whatsapp_fl_ativo_check CHECK ((fl_ativo = ANY (ARRAY[0, 1]))),
	CONSTRAINT canal_whatsapp_numero_e164_check CHECK (((numero_e164)::text ~ '^\+[1-9][0-9]{6,15}$'::text)),
	CONSTRAINT canal_whatsapp_pkey PRIMARY KEY (id_canal_whatsapp),
	CONSTRAINT fk_cw_empresa FOREIGN KEY (id_empresa) REFERENCES dbo.empresa(id_empresa)
);


-- dbo.empresa_aplicacao definition

-- Drop table

-- DROP TABLE dbo.empresa_aplicacao;

CREATE TABLE dbo.empresa_aplicacao (
	id_empresa_aplicacao uuid DEFAULT gen_random_uuid() NOT NULL,
	id_empresa uuid NOT NULL,
	id_aplicacao uuid NOT NULL,
	fl_ativo int2 DEFAULT 1 NOT NULL,
	CONSTRAINT empresa_aplicacao_fl_ativo_check CHECK ((fl_ativo = ANY (ARRAY[0, 1]))),
	CONSTRAINT empresa_aplicacao_pkey PRIMARY KEY (id_empresa_aplicacao),
	CONSTRAINT fk_ea_aplicacao FOREIGN KEY (id_aplicacao) REFERENCES dbo.aplicacao(id_aplicacao),
	CONSTRAINT fk_ea_empresa FOREIGN KEY (id_empresa) REFERENCES dbo.empresa(id_empresa)
);


-- dbo.prompt definition

-- Drop table

-- DROP TABLE dbo.prompt;

CREATE TABLE dbo.prompt (
	id_prompt uuid DEFAULT gen_random_uuid() NOT NULL,
	id_agente uuid NOT NULL,
	tipo varchar NOT NULL,
	titulo varchar NULL,
	conteudo text NOT NULL,
	ordem int4 DEFAULT 0 NOT NULL,
	criado_em timestamp DEFAULT now() NOT NULL,
	CONSTRAINT prompt_pkey PRIMARY KEY (id_prompt),
	CONSTRAINT fk_pr_agente FOREIGN KEY (id_agente) REFERENCES dbo.agente(id_agente)
);


-- dbo.usuario_empresa definition

-- Drop table

-- DROP TABLE dbo.usuario_empresa;

CREATE TABLE dbo.usuario_empresa (
	id_usuario uuid NOT NULL,
	id_empresa uuid NOT NULL,
	papel varchar NULL,
	criado_em timestamp DEFAULT now() NOT NULL,
	fl_ativo int2 DEFAULT 1 NOT NULL,
	CONSTRAINT usuario_empresa_fl_ativo_check CHECK ((fl_ativo = ANY (ARRAY[0, 1]))),
	CONSTRAINT usuario_empresa_pkey PRIMARY KEY (id_usuario, id_empresa),
	CONSTRAINT fk_ue_empresa FOREIGN KEY (id_empresa) REFERENCES dbo.empresa(id_empresa),
	CONSTRAINT fk_ue_usuario FOREIGN KEY (id_usuario) REFERENCES dbo.usuario(id_usuario)
);


-- dbo.aplicacao_canal definition

-- Drop table

-- DROP TABLE dbo.aplicacao_canal;

CREATE TABLE dbo.aplicacao_canal (
	id_aplicacao_canal uuid DEFAULT gen_random_uuid() NOT NULL,
	id_aplicacao uuid NOT NULL,
	id_empresa uuid NOT NULL,
	id_empresa_aplicacao uuid NOT NULL,
	conta int4 NULL,
	identificador varchar NULL,
	fl_ativo int2 DEFAULT 1 NOT NULL,
	provider varchar DEFAULT 'chatwoot'::character varying NULL,
	chatwoot_base_url text NULL,
	chatwoot_account_id int4 NULL,
	chatwoot_inbox_id int4 NULL,
	chatwoot_token_ref text NULL,
	meta_json jsonb DEFAULT '{}'::jsonb NULL,
	id_agente uuid NULL,
	chatwoot_token text NULL,
	canal_composto varchar NULL,
	chatwoot_teams_department_id int4 NULL,
	instancia_evolution varchar NULL,
	CONSTRAINT aplicacao_canal_fl_ativo_check CHECK ((fl_ativo = ANY (ARRAY[0, 1]))),
	CONSTRAINT aplicacao_canal_pkey PRIMARY KEY (id_aplicacao_canal),
	CONSTRAINT fk_ac_agente FOREIGN KEY (id_agente) REFERENCES dbo.agente(id_agente),
	CONSTRAINT fk_ac_aplicacao FOREIGN KEY (id_aplicacao) REFERENCES dbo.aplicacao(id_aplicacao),
	CONSTRAINT fk_ac_ea FOREIGN KEY (id_empresa_aplicacao) REFERENCES dbo.empresa_aplicacao(id_empresa_aplicacao),
	CONSTRAINT fk_ac_empresa FOREIGN KEY (id_empresa) REFERENCES dbo.empresa(id_empresa)
);


-- dbo.aplicacao_canal__canal_whatsapp definition

-- Drop table

-- DROP TABLE dbo.aplicacao_canal__canal_whatsapp;

CREATE TABLE dbo.aplicacao_canal__canal_whatsapp (
	id_aplicacao_canal uuid NOT NULL,
	id_canal_whatsapp uuid NOT NULL,
	principal bool DEFAULT true NOT NULL,
	fl_ativo int2 DEFAULT 1 NOT NULL,
	CONSTRAINT aplicacao_canal__canal_whatsapp_fl_ativo_check CHECK ((fl_ativo = ANY (ARRAY[0, 1]))),
	CONSTRAINT aplicacao_canal__canal_whatsapp_pkey PRIMARY KEY (id_aplicacao_canal, id_canal_whatsapp),
	CONSTRAINT fk_accw_canal FOREIGN KEY (id_aplicacao_canal) REFERENCES dbo.aplicacao_canal(id_aplicacao_canal),
	CONSTRAINT fk_accw_num FOREIGN KEY (id_canal_whatsapp) REFERENCES dbo.canal_whatsapp(id_canal_whatsapp)
);


-- dbo.aplicacao_canal_whatsapp definition

-- Drop table

-- DROP TABLE dbo.aplicacao_canal_whatsapp;

CREATE TABLE dbo.aplicacao_canal_whatsapp (
	id_aplicacao_canal uuid NOT NULL,
	business_id varchar NULL,
	business_conta varchar NULL,
	webhook_url text NULL,
	CONSTRAINT aplicacao_canal_whatsapp_pkey PRIMARY KEY (id_aplicacao_canal),
	CONSTRAINT fk_acw_canal FOREIGN KEY (id_aplicacao_canal) REFERENCES dbo.aplicacao_canal(id_aplicacao_canal)
);